import React, { useState, useEffect } from 'react';
import { getCommonPlantDiseases } from '../services/geminiService';
import { DiseaseInfo } from '../types';
import Spinner from '../components/Spinner';
import { AlertTriangleIcon } from '../components/Icons';

const DiseaseLibraryPage: React.FC = () => {
  const [diseases, setDiseases] = useState<DiseaseInfo[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchDiseases = async () => {
      try {
        setIsLoading(true);
        setError(null);
        const diseaseList = await getCommonPlantDiseases();
        setDiseases(diseaseList);
      } catch (err: any) {
        setError(err.message || "An unexpected error occurred.");
      } finally {
        setIsLoading(false);
      }
    };

    fetchDiseases();
  }, []);

  return (
    <div className="space-y-8">
      <header className="text-center animate-swoop-in-down">
        <h1 className="text-3xl md:text-4xl font-bold text-green-900">Disease Library</h1>
        <p className="mt-3 text-base md:text-lg text-gray-600">A guide to common plant ailments, generated by AI.</p>
      </header>

      {isLoading && <Spinner />}
      
      {error && (
        <div className="flex items-center gap-3 bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-lg animate-fade-in max-w-2xl mx-auto" role="alert">
          <AlertTriangleIcon className="h-6 w-6" />
          <div>
            <p className="font-bold">Error Loading Library</p>
            <p>{error}</p>
          </div>
        </div>
      )}

      {!isLoading && !error && (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {diseases.map((disease, index) => (
            <div 
              key={disease.name} 
              className="bg-white p-6 rounded-lg shadow-lg hover:shadow-xl hover:-translate-y-1 transition-all duration-300 stagger-fade-in"
              style={{ animationDelay: `${index * 50}ms` }}
            >
              <h3 className="text-xl font-bold text-green-800 mb-2">{disease.name}</h3>
              <p className="text-gray-700 text-sm leading-relaxed">{disease.description}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};

export default DiseaseLibraryPage;